name: Docker-build-push

on:
  workflow_dispatch:
    inputs:
      typetag:
        description: 'Type a tag to run'
        required: true
        default: 'dev'

jobs:
  build-arm64:
    runs-on: ubuntu-24.04-arm
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    #  - name: Set up QEMU
    #    uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      - name: Build and push to local registry
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64
          tags: localhost:5000/nhatnhat011/aura-bot:${{ github.event.inputs.typetag }}-arm64

  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      - name: Build and push to local registry
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64
          tags: localhost:5000/nhatnhat011/aura-bot:${{ github.event.inputs.typetag }}-amd64
      - name: Create SHA manifest and push
        run: |
          docker manifest create \
            nhatnhat011/aura-bot:${{ github.event.inputs.typetag }} \
            --amend localhost:5000/nhatnhat011/aura-bot:${{ github.event.inputs.typetag }}-arm64 \
            --amend localhost:5000/nhatnhat011/aura-bot:${{ github.event.inputs.typetag }}-amd64
          docker manifest push nhatnhat011/aura-bot:${{ github.event.inputs.typetag }}
