name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      typetag:
        description: 'Type a tag to run'
        required: true
        default: 'integration'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nhatnhat011/aura-bot:${{ github.event.inputs.typetag }}
